// Field constants come from the official field CAD (cad/field-manifest.json,
// generated by scripts/convert-step.mjs) and the Competition Manual TU01.
// Coordinates match the CAD: X red -> blue, Y up, Z rear -> audience. Meters.

export const IN = 0.0254;

export const FIELD = {
  half: 1.7929,            // Inner face of the perimeter wall (tile edge in CAD).
  wallHeight: 0.3228,
  wallThickness: 0.03,
  pollenRadius: 0.03556,   // 2.8 in. diameter
  nectarRadius: 0.04572,   // 3.6 in. diameter
  // Zones from the gaffer-tape bounding boxes in CAD: [xMin, xMax, zMin, zMax].
  loadingZone: { red: [-1.7929, -1.5012, -1.1836, -0.6072], blue: [1.5012, 1.7929, 0.6072, 1.1836] },
  garden: { red: [-1.7806, -1.2042, 1.7298, 1.7929], blue: [1.2042, 1.7806, -1.7929, -1.7298] },
  // Flower centers (X, Z) from the staged POLLEN in CAD, and the wall each is on.
  flowers: [
    { id: 'rear', x: -0.5942, z: -1.7282 },
    { id: 'audience', x: 0.5942, z: 1.7282 },
    { id: 'red', x: -1.7282, z: 0.5942 },
    { id: 'blue', x: 1.7282, z: -0.5942 },
  ],
  flowerHalfSize: 0.0847,  // Half of the 0.169 m flower footprint in CAD.
  flowerTop: 0.546,        // Top ring, 21.5 in.
  flowerScoreBottom: 0.101, // Top of the middle ring: 9.0 cm opening + 1.1 cm ring.
  // The middle ring passes POLLEN but retains NECTAR (G418: only POLLEN leaves through the bottom).
  flowerNectarSeat: 0.09,
  flowerPlaceLimit: 0.506,  // A new element needs its bottom under this height to stay in the FLOWER.
  nectarStash: 5,
} as const;

// Hive geometry in the hive-local frame: pivot at the origin, hive level,
// rear CELL toward -Z. Values are bounding boxes of the CAD skins.
export const HIVE = {
  pivotY: 1.11655,
  pivotX: { red: -0.3237, blue: 0.3241 },
  tiltLimit: Math.PI / 6,        // 30 degrees, Figure 9-10
  cellBack: 0.2396,              // Back skin distance from the pivot
  cellMouth: 0.545,
  cellHalfWidth: 0.2565,
  cellFloorY: -0.036,
  cellSideTopY: 0.1605,
  cellPeakY: 0.3224,
  wall: 0.012,                   // Collider thickness
  // Frame parts from the CAD. The foot bar (am-5878) sits on top of the TILES and blocks a robot.
  // Each leg (am-5876) runs from its foot to the top corner and leans inward in both X and Z.
  footBar: { x: 0.603, halfX: 0.025, halfZ: 0.495, height: 0.055 },
  legFoot: { x: 0.598, y: 0.03, z: 0.46 }, legTop: { x: 0.325, y: 1.05, z: 0.0 }, legSize: 0.0254,
} as const;

// Ball masses are AndyMark's listed weights. Their ratio is 1.65, and the Event Field Setup Guide needs a ratio under
// 1.667, because it states that 3 POLLEN + 3 NECTAR weigh less than 8 POLLEN. The hive ballast is calibrated against
// these masses. Restitution, friction, and damping are still estimates.
export const BALL = {
  // AndyMark's product page for the BIOBUZZ scoring elements lists POLLEN (am-5851) at 0.055 lb and NECTAR (am-5852)
  // at 0.091 lb. The Competition Manual, section 9.8, gives no weight: it says that both are Gopher ResisDent
  // polyethylene balls. scripts/ball-mass.mjs cross-checks the weights against the CAD: the NECTAR model holds 42.8 cm³
  // of plastic, which is 40.7 g at 0.95 g/cm³, and the POLLEN model holds 22.2 cm³, which is 21.0 g.
  pollenMass: 0.055 * 0.45359237, // 24.9 g
  nectarMass: 0.091 * 0.45359237, // 41.3 g
  restitution: 0.45,
  friction: 0.6,
  linearDamping: 0.12,
  angularDamping: 1.2,
  airDensity: 1.2, dragCd: 0.47,
};

// Hive dynamics. `comHeight` is the ballast-washer equivalent: it sets the
// tipping point. test/hive-calibration.test.ts checks the value against the
// six rows of Event Field Setup Guide section 12.3.
export const HIVE_DYN = {
  mass: 1.4,
  inertia: 0.16,          // About the pivot axis, kg m^2
  comHeight: 0.063,       // Calibrated with the AndyMark ball masses: 0.060 to 0.066 passes all six rows. See docs/hive-calibration.md.
  pivotFriction: 0.012,   // Coulomb friction torque, N m
  damperZone: 0.14,       // The damper engages within this angle of a stop, rad
  damperCoeff: 0.9,       // N m s per rad while closing on a stop
};

export type ShooterType = 'catapult' | 'fifo' | 'dual';
export interface Dist { mean: number; std: number }
export interface LaunchParams {
  offset: [number, number, number]; // Launch point in the robot frame: forward, left, up. Meters.
  elevationDeg: Dist;
  speed: Dist;                      // m/s
  yawStdDeg: number;
  backspinRpm: Dist;
}
export interface RobotConfig {
  length: number; width: number; height: number; mass: number; yawInertia: number;
  wheelRadius: number; halfWheelbase: number; halfTrack: number;
  motor: { freeRpm: number; stallTorque: number; stallCurrent: number; freeCurrent: number };
  battery: { openCircuitV: number; resistance: number };
  gearEfficiency: number; strafeEfficiency: number; wheelMu: number; rollingResistance: number; viscousLoss: number;
  capacity: number;
  /** `dualSided` adds a second intake on the rear face, so the robot collects floor elements from either end. Default: false. POLLEN still comes out of a FLOWER at the front only. */
  intake: { width: number; reach: number; successP: number; retrySec: number; flowerReach: number; flowerPeriodSec: number; dualSided?: boolean };
  /** `facing: 'rear'` launches out of the side opposite the intake, so the robot turns less between pickup and launch. */
  /**
   * `dualSided` lets the robot launch out of either end, for example with a two-position turret or two catapults. It
   * launches out of the end that faces its own HIVE. Default: false.
   * `turret` mounts the shooter on a turret with full range of motion and an instant slew: each launch aims at the
   * raised CELL's mouth of the robot's own HIVE, whatever the robot's heading. It's an upper bound: a real turret has
   * limits, so it can only do worse. It overrides `dualSided` and `facing`. Default: false.
   */
  shooter: { type: ShooterType; facing: 'front' | 'rear'; cycleSec: number; pollen: LaunchParams; nectar: LaunchParams; dualSided?: boolean; turret?: boolean };
  place: { range: number; maxBearingDeg: number; durationSec: number; successP: number };
  /**
   * The AprilTag camera. It faces the same side as the shooter and looks up at the underside of the raised CELL.
   * `offset` is forward, left, up in meters, with forward measured toward the shooter side.
   */
  camera: { offset: [number, number, number]; pitchDeg: number; hFovDeg: number; vFovDeg: number; maxRange: number; maxIncidenceDeg: number };
}

export const DEFAULT_ROBOT: RobotConfig = {
  length: 0.43, width: 0.43, height: 0.30, mass: 13, yawInertia: 0.42,
  wheelRadius: 0.052,            // goBILDA 104 mm mecanum
  halfWheelbase: 0.168, halfTrack: 0.19,
  // goBILDA 5203 Yellow Jacket, 13.7:1 (435 rpm) at 12 V, from the goBILDA spec sheet.
  motor: { freeRpm: 435, stallTorque: 1.834, stallCurrent: 9.2, freeCurrent: 0.25 },
  battery: { openCircuitV: 12.8, resistance: 0.11 },
  gearEfficiency: 0.9, strafeEfficiency: 0.72, wheelMu: 0.6, rollingResistance: 0.03,
  viscousLoss: 12,               // N s per m. Roller and gearbox losses that grow with speed.
  capacity: 4,                   // G407
  intake: { width: 0.34, reach: 0.07, successP: 0.95, retrySec: 0.6, flowerReach: 0.13, flowerPeriodSec: 0.35 },
  shooter: {
    type: 'dual', facing: 'rear', cycleSec: 0.3,
    pollen: { offset: [0.05, 0, 0.36], elevationDeg: { mean: 67, std: 1.0 }, speed: { mean: 5.35, std: 0.08 }, yawStdDeg: 1.2, backspinRpm: { mean: 900, std: 100 } },
    nectar: { offset: [0.05, 0, 0.36], elevationDeg: { mean: 67, std: 1.2 }, speed: { mean: 5.3, std: 0.1 }, yawStdDeg: 1.5, backspinRpm: { mean: 700, std: 100 } },
  },
  place: { range: 0.32, maxBearingDeg: 30, durationSec: 0.6, successP: 0.9 },
  // Limelight 3A: 54.5 x 42 degree field of view at 640 x 480 (Limelight documentation). It sits at the shooter-side
  // edge, 0.30 m up, pitched 50 degrees: from the launch spots the raised CELL's tags are about 50 degrees above the
  // horizon and 1.3 m away. ASSUMPTION: a 3.25 in. tag is readable to 2.6 m, where it spans 20 pixels, and up to 70
  // degrees off its normal. Limelight publishes no range figure.
  camera: { offset: [0.15, 0, 0.3], pitchDeg: 50, hFovDeg: 54.5, vFovDeg: 42, maxRange: 2.6, maxIncidenceDeg: 70 },
};

/**
 * Sets the drive motor's free speed by changing the gear ratio of the same motor: the stall torque scales inversely.
 * The reference is the goBILDA 5203 at 435 rpm and 1.834 N m (goBILDA spec sheet).
 */
export function setDriveRpm(c: RobotConfig, rpm: number) { c.motor.freeRpm = rpm; c.motor.stallTorque = (DEFAULT_ROBOT.motor.stallTorque * DEFAULT_ROBOT.motor.freeRpm) / rpm; }
/** Sets the robot mass in kilograms and scales the yaw inertia with it. R102 limits a robot to 42 lb (19.05 kg). Call it after `setSquareSize`. */
export function setMass(c: RobotConfig, kg: number) { c.yawInertia *= kg / c.mass; c.mass = kg; }
/** Sets a square chassis size in meters and scales the wheelbase, the track, the intake width, and the yaw inertia with it. R101 limits a robot to 18 in. (0.457 m). */
export function setSquareSize(c: RobotConfig, m: number) { const k = m / DEFAULT_ROBOT.length; c.length = c.width = m; c.halfWheelbase = DEFAULT_ROBOT.halfWheelbase * k; c.halfTrack = DEFAULT_ROBOT.halfTrack * k; c.intake.width = m - 0.09; c.yawInertia = DEFAULT_ROBOT.yawInertia * k * k; }

// Load in the raised CELL, in POLLEN equivalents, at which the HIVE tips. It follows from the calibration
// standard with NECTAR at 1.65, the ratio of the listed masses: 7 POLLEN (7.0) and 3 NECTAR + 2 POLLEN (6.95) hold; 3 NECTAR + 3 POLLEN (7.95) tips.
export const TIP_LOAD = { threshold: 7.4, pollen: 1, nectar: 1.65 };

export const POINTS = { leave: 3, park: 5, tip: 20, cell: 2, bottomNectar: 5, flower: 2, garden: 1 };
/**
 * Ranking point thresholds. `win` and `tie` are the ranking points for the MATCH result. They follow the 2025-2026
 * Competition Manual's ranking point table (3 for a win, 1 for a tie). I haven't checked them against the BIOBUZZ manual.
 */
export const RP = { swarm: 16, pollinator1: 4, pollinator2: 7, win: 3, tie: 1 };
export const MATCH = { auto: 30, transition: 8, teleop: 120, flowerUnlock: 60 };
